### ISSUE TITLE
ubuntu18.04 无法启动

### ISSUE THREAD

**Issue by hecanbo** [busyluo/mNetAssist#1]
ubuntu18.04 可以安装，但无法启动  mNetAssist-release-amd64.deb. 作者能解决下吗，谢谢！

**Comment by busyluo** [comment]
这个deb是你自己打包的吧

**Comment by hecanbo** [comment]
能看到你有回复，太棒了。不是我自己打的包，从别人的网盘里下载的。我还不会用qt5,作者能给我一个deb包吗，谢谢。hecb999@126.com
网上搜索了下，好象全都是你写的这个. 我主要是想在ubuntu下使用。

**Comment by busyluo** [comment]
自己编译运行吧,
1. Ubuntu 下，sudo apt install qt4-qmake libqt4-dev
2. qmake && make

**Comment by hecanbo** [comment]
搞定，非常感谢
